#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

submenu isoboot {
  menuentry "SystemRescue" {
    iso_path="/isoboot/systemrescue.iso"
    export iso_path
    search --set=root --file $iso_path
    # support booting recent GRUB versions on UEFI systems
    rmmod tpm
    loopback loop $iso_path
    set root=(loop)
    # the path below is on the SystemRescue ISO, not the hard drive
    configfile /boot/grub/loopback.cfg
  }
}
